# Generated by Django 4.2.11 on 2024-05-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='description',
            field=models.TextField(default='Description'),
        ),
    ]
