# Generated by Django 4.2.11 on 2024-05-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0003_aboutinfo_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutinfo',
            old_name='profile_image',
            new_name='image',
        ),
    ]
