# Generated by Django 4.2.11 on 2024-05-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
