# Generated by Django 4.2.11 on 2024-05-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_about', '0002_aboutinfo_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutinfo',
            name='is_authenticated',
        ),
    ]
