# Generated by Django 4.2.11 on 2024-05-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_about', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
