# Generated by Django 4.2.11 on 2024-05-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_about', '0009_rename_profile_image_aboutinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='image',
            field=models.ImageField(default='default_profile.jpg', upload_to='galerie'),
        ),
    ]
